# Generated by Django 4.2.17 on 2024-12-08 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='showcases', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_showcases', to='core.showcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_showcases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'showcase')},
            },
        ),
    ]
