# Generated by Django 4.2.18 on 2025-01-20 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usershowcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_showcases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showcase',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='showcases', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='usershowcase',
            unique_together={('user', 'showcase')},
        ),
    ]
