# Generated by Django 4.2.18 on 2025-01-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
